### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by reginfo** [asand3r/zbx-hpmsa#1]
Hi, 

I`m having a problem with running this script from zabbix.

If I`m running script prom SSH - ALL OK.
But from zabbix Latest Data :
> Traceback (most recent call last):  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open    h.request(req.get_method(), req.selector, req.data, headers)  File "/usr/lib/python3.5/http/client.py", line 1106, in request    self._send_reque
> --

How to fix? 

BR,
Deniss

**Comment by asand3r** [comment]
Hi,
It's rather hard to debug with way, I mean remotelly , but I looked at sources of request.py and it says what it maybe error by timeout:
```
try:
                h.request(req.get_method(), req.selector, req.data, headers)
            except OSError as err: # timeout error
                raise URLError(err)
```
So, maybe you should try temporary increase script execution time on zabbix server and check it again?

**Comment by reginfo** [comment]
I`m using proxy (another location).
Zabbix Proxy Conf timeout is set to 30. On a Server it is also 30. 

As I execute script from root - ALL OK.
I try to simulate execution from root using zabbix user:
sudo -H -u zabbix bash -c './zbx-hpmsa.py --msa 192.168.0.205 --component disks --get 1.1'
OK

We can try to do remote session, if it will help!

**Comment by asand3r** [comment]
Interesting. Are you do this with one storage or it's two different? I mean, you connecting to only one MSA via directly running script and script running from Zabbix Server?
Also, could you show me your Item in Zabbix?
I think I'll make some correction in script tomorrow to make easy to understand http errors and we'll try it again.

**Comment by reginfo** [comment]
It is one MSA2040 dual controller at customer site. 
I connect to zabbix proxy via ssh and perform all script execution tasks.

I added host using agent interface and attached your template.
In discovery I see 
> zbx-hpmsa.py["-d", "-m", "{HOST.CONN}", "-c", "disks"]
> zbx-hpmsa.py["-d", "-m", "{HOST.CONN}", "-c", "vdisks"]

After discovery time, in items i see these items:
![capture](https://user-images.githubusercontent.com/4628571/28168365-925f8c12-67e7-11e7-8ec3-b467a2fe98d2.JPG)
![capture4](https://user-images.githubusercontent.com/4628571/28168679-833493a8-67e8-11e7-8f67-0cc14c07d1c1.JPG)

But I took one of discovered item and cloned with hardcoded IP address, and everything seems working. 
![capture2](https://user-images.githubusercontent.com/4628571/28168410-b53809d0-67e7-11e7-8ba4-e14fbe022801.JPG)
![capture3](https://user-images.githubusercontent.com/4628571/28168435-c41da20c-67e7-11e7-9cbf-79a59c110c80.JPG)

Zabbix Server 3.2.3
Zabbix Proxy 3.2.4

**Comment by asand3r** [comment]
OK, I think the problem with macros {HOST.CONN} - it should unfold (hope it's right word) to IP address or DNS name, so it may be DNS issue. I think you know what {HOST.CONN} takes from here:
![capture](https://user-images.githubusercontent.com/13959303/28168978-8063e470-67e9-11e7-9eb9-9b1d182be0dc.PNG)
And maybe if you host configured with DNS name, your proxy cannot resolve it to IP.

**Comment by reginfo** [comment]
I Use only IP addressed, not DNS names. 
So I recreate a Host
![capture5](https://user-images.githubusercontent.com/4628571/28169876-4bc46d22-67ec-11e7-85fc-8a52a2b5ee04.JPG)
and still the same problem
![capture6](https://user-images.githubusercontent.com/4628571/28169928-7369f5ae-67ec-11e7-83be-33aed01b3b37.JPG)

**Comment by asand3r** [comment]
But if you not use my template and create items yourself all works fine?

**Comment by reginfo** [comment]
For test I used clone of item from your template and changed {HOST.CONN} to real IP. 
And last value is OK

**Comment by asand3r** [comment]
Hey, I've just uploaded new version with some emproves in work with HTTP, so now we should get more understandable error. Could you check it?
https://github.com/asand3r/zbx-hpmsa/tree/master/0.2.4

**Comment by reginfo** [comment]
root@ZBX:/usr/local/share/zabbix/externalscripts# ./zbx-hpmsa.py -d --msa 192.168.0.205 --component disks
./zbx-hpmsa.py: line 7: syntax error near unexpected token `newline'
./zbx-hpmsa.py: line 7: `<!DOCTYPE html>'

**Comment by asand3r** [comment]
Hm, 7 line is library import. Could you try execute:
from urllib.error import URLError
in Python console?

It's strange, because in my desktop (Python 3.5.3) and server (CentOS 7.3.1611, python 3.4) it works fine. What is your environment?

**Comment by reginfo** [comment]
My fault, code was incorrect loaded/downloaded.

**Comment by reginfo** [comment]
The same problem with Traceback (most recent call last).

Isn`t it related that in discovery we use {HOST.CONN} but in the item we use {HOST.NAME}????
I changed {HOST.NAME} to {HOST.CONN} and seems it works!

**Comment by asand3r** [comment]
Damn, yes, I forget to change HOST.NAME to HOST.CONN in template. =)
Thank you, I'll update Template file to using {HOST.CONN} macro.
