### ISSUE TITLE
Zabbix returning a Value should be a JSON object

### ISSUE THREAD

**Issue by jwatsonuk** [asand3r/zbx-hpmsa#11]
Hi,

I have downloaded and uploaded your script to our zabbix server. The script runs fine from command line but when i uploaded the template and created the item/MSA to monitor. Zabbix comes back with the following error against the discovery rules "Value should be a JSON object".

Could you give me some guidance that I have set up the item correctly? I will uploaded screenshots of the item properties and the error message i see.

Thanks,

James

![image](https://user-images.githubusercontent.com/42766314/44710362-dbdec100-aaa3-11e8-9673-e7cbac5b5dd4.png)

![image](https://user-images.githubusercontent.com/42766314/44710385-f153eb00-aaa3-11e8-96ae-c3432d448c5d.png)

![image](https://user-images.githubusercontent.com/42766314/44710401-ff097080-aaa3-11e8-93fa-5eb14e09ffbd.png)

**Comment by asand3r** [comment]
Hi, @jwatsonuk,

Please, read Wiki page "Requirements and Installation".
https://github.com/asand3r/zbx-hpmsa/wiki/Requirements-and-Installation

> but if you ran the utility first time under another account (e.g. root), directory was created with his owns and 777 (755 before v0.5.x) permissions. So you must redefine the rights or delete the directory and the utility will create it self.

It should be your case.

**Comment by jwatsonuk** [comment]
Hi @asand3r,

Thank you for your response.

I have realised that i have missed a step in your guide. It regarding the folder that the utility creates on the first run. I have changed the permission of that folder to 777. 

I'm just retrying the item on zabbix. I will keep you updated.

James

**Comment by asand3r** [comment]
You can just delete it and script will create it self with all needed permissions. I'll add permissions checking in next version, because I'm receiving there are a lot of messages about it. =)

**Comment by jwatsonuk** [comment]
Hi,

I did delete that file and the script recreated with the correct permissions for zabbix:zabbix but im still getting "Value should be a JSON Object" on the discovery rules.

Here is the screenshot from the terminal;

![image](https://user-images.githubusercontent.com/42766314/44716501-662e2180-aab2-11e8-903e-258fbe4becb9.png)

Thanks,

James

**Comment by asand3r** [comment]
OK.  So, it's LLD and to debug it you must check Zabbix server log (3 or 4 level shows LLD messages). But! If in console you can get right data and Zabbix shows 'Value should be a JSON object', I think it's old meesage. Try to change update interval to 1m or similar and wait.

**Comment by jwatsonuk** [comment]
I have fixed the issue. 

I noticed that password for the MSA had some special characters. So i created another user for zabbix and made a simple password for it. 

It is now discovering the items. 

Thanks for your help.

**Comment by jwatsonuk** [comment]
Here is an example of the password that was used previously; !SEfZQW4Yn=PSwBAc

Also I forgot to mention that I did re added the script (zbx-hpmsa.py).
