### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by inkostin** [asand3r/zbx-hpmsa#12]
https://d.radikal.ru/d11/1809/b3/c992c6f17b4c.png

**Comment by asand3r** [comment]
Привет,

1. v0.5.6?
2. Скорее всего проблема с правами на БД с кешом (/dev/shm/zbx-hpmsa/zbx-hpmsa.cache.db)

Удали каталог /dev/shm/zbx-hpmsa/ и подожди пока скрипт сам не создаст его.

**Comment by inkostin** [comment]
Да, последняя.

Так там и нет, такого каталога.

root@zabbix:/dev/shm# ls -la /dev/shm
total 0
drwxrwxrwt  2 root root   40 Sep 12 17:37 .
drwxr-xr-x 16 root root 2960 Sep 12 17:37 ..

Правильно же:
https://a.radikal.ru/a17/1809/5d/51ee61853fbf.png

**Comment by asand3r** [comment]
Нет, не правильно. Почему адрес MSA указан как 127.0.0.1?

**Comment by inkostin** [comment]
show snmp-parameters
SNMP Parameters
---------------
SNMP Trap Notification Level: none
SNMP Trap Host IP1: 0.0.0.0
SNMP Trap Host IP2: 0.0.0.0
SNMP Trap Host IP3: 0.0.0.0
SNMP read community: public
SNMP write community: public

https://a.radikal.ru/a15/1809/08/d781f9f55010.png
Но он почему-то зеленым не горит...(

**Comment by asand3r** [comment]
Честно говоря, я ничего не вижу на скриншоте. Это как-то связано со скриптом zbx-hpmsa?

**Comment by inkostin** [comment]
https://d.radikal.ru/d42/1809/4a/85b7dee0478f.png

По идее [SNMP] в шаблоне должен гореть зеленым или нет?

**Comment by asand3r** [comment]
По идее. Но это уже вопрос к тому, как Zabbix определяет доступность протокола у хоста.

**Comment by inkostin** [comment]
А как проверить руками из командной строки?
./zbx-hpmsa.py - с какими ключами?

**Comment by asand3r** [comment]
@inkostin давай так - вот тебе ссылка на Wiki: https://github.com/asand3r/zbx-hpmsa/wiki
Будут вопросы - без проблем отвечу в Telegram. =) А т.к. это не баг -этот issue я закрою.

**Comment by inkostin** [comment]
Нет Телеграмма, может по почте?

./zbx-hpmsa.py --msa 172.16.1.1 -c disks -g all
{"1.1":{"health":"OK","health-num":"0","error":"0","temperature":"29","power-on-hours":"25878"},"1.2":{"health":"OK","health-num":"0","error":"0","temperature":"27","power-on-hours":"25877"}, ... }

root@zabbix:/usr/lib/zabbix/externalscripts# ./zbx-hpmsa.py --msa "мой IP" -c disks -g all
usage: zbx-hpmsa.py [-h] [-a {1,2}] [-u USERNAME] [-p PASSWORD]
                    [-f LOGIN_FILE] [-v] [-s SAVE_XML] [-t TMP_DIR]
                    [--ssl {direct,verify}]
                    {install,cache,lld,full,health} ...
zbx-hpmsa.py: error: argument command: invalid choice: '"мой IP"' (choose from 'install', 'cache', 'lld', 'full', 'health')

Может инструкцию простенькую?

**Comment by asand3r** [comment]
Сверху пример для версии скрипта 0.5.x. Ниже вывод от версии 0.6, которую я выпустил вчера - там синтаксис поменялся. На главной странице есть описания различий и примеры использования.
Вкратце, теперь LLD выглядит так:
./zbx-hpmsa.py lld 172.16.1.1 disks
Получение данных:
./zbx-hpmsa.py full 172.16.1.1 disks

По ключу -h доступна справка.

**Comment by inkostin** [comment]
ERROR: unable to open database file
ERROR: unable to open database file
ERROR: unable to open database file
ERROR: 2 : Invalid sessionkey

Но так как базы нет, то логично...(

**Comment by asand3r** [comment]
1. ./zbx-hpmsa.py install
2. ./zbx-hpmsa.py lld 172.16.1.1 disks

**Comment by inkostin** [comment]
База создалась:
root@zabbix:/dev/shm# ls -la /dev/shm/zbx-hpmsa
total 12
drwxrwxr-x 2 root zabbix    60 Sep 14 11:50 .
drwxrwxrwt 3 root root      60 Sep 14 11:50 ..
-rw-rw-r-- 1 root zabbix 12288 Sep 14 11:50 zbx-hpmsa.cache.db

root@zabbix:/dev/shm#
root@zabbix:/dev/shm/zbx-hpmsa# ls -la zbx-hpmsa.cache.db
-rw-rw-r-- 1 root zabbix 12288 Sep 14 11:50 zbx-hpmsa.cache.db

Но:
./zbx-hpmsa.py lld IP disks
ERROR: 2 : Invalid sessionkey

**Comment by asand3r** [comment]
Что за хранилище?

**Comment by inkostin** [comment]
SQlite 3 format

**Comment by asand3r** [comment]
Я про модель MSA. =)

**Comment by inkostin** [comment]
Bundle Version: VL270R001-01
System Information: HPE MSA Storage 2050
=)

**Comment by asand3r** [comment]
Хорошо, с 2050 у меня всё протестировано и проблем нет. Я бы хотел посмотреть вживую ошибку. Можно организовать какое-то удаленное подключение? TeamViwer, например.

**Comment by inkostin** [comment]
Вот с P2000 G3 проблем нет =)
./zbx-hpmsa.py lld IP volumes
{"data":[{"{#VOLUME.TYPE}":"standard","{#VOLUME.ID}":"vd01_v000"},{"{#VOLUME.TYPE}":"standard","{#VOLUME.ID}":"vd02_v001"},{"{#VOLUME.TYPE}":"standard","{#VOLUME.ID}":"vd03_v001"}]}

**Comment by asand3r** [comment]
![default](https://user-images.githubusercontent.com/13959303/45542674-3fdee480-b81b-11e8-9b88-78c3ddfe5120.png)

**Comment by inkostin** [comment]
Bundle Version: VL270R001-01
У Вас:
VL100P001

**Comment by asand3r** [comment]
Я знаю. Это версия прошивки. Не думаю, что API сменился от версии к версии.

**Comment by inkostin** [comment]
А: show protocols ?

**Comment by asand3r** [comment]
HTTP, HTTPS.

**Comment by asand3r** [comment]
Мне нужен TeamViewer ) гадать дальше я не могу.

**Comment by inkostin** [comment]
Тогда в почту.(kobra1999@mail.ru)

**Comment by asand3r** [comment]
Попробуй исполняемый файл из ветки 0.5.7:
https://github.com/asand3r/zbx-hpmsa/tree/v0.5.7

**Comment by asand3r** [comment]
Я закрываю issue?

**Comment by inkostin** [comment]
да
