### ISSUE TITLE
MSA 2052 Issue

### ISSUE THREAD

**Issue by mitnoleg** [asand3r/zbx-hpmsa#13]
**Describe the bug**
There is no information of consumption of psu;
Disk cache status;

**Screenshots**
MSA2052 Licence
![2018-10-30_083302](https://user-images.githubusercontent.com/35614700/47698096-07eefd80-dc1f-11e8-9b4d-3c634983c454.png)
Data of PSU
![2018-10-30_082949](https://user-images.githubusercontent.com/35614700/47698144-3e2c7d00-dc1f-11e8-8f14-e68ea72daf05.png)
Disk cache status
![2018-10-30_082831](https://user-images.githubusercontent.com/35614700/47698283-c6128700-dc1f-11e8-97bb-62f2d25c4d89.png)
Disk cache
![2018-10-30_084923](https://user-images.githubusercontent.com/35614700/47698546-ceb78d00-dc20-11e8-9353-38cc91c60f20.png)
MSA JSON power-supplies full
![2018-10-30_084435](https://user-images.githubusercontent.com/35614700/47698359-1be72f00-dc20-11e8-9f6f-afc6896afd1d.png)
MSA JSON disk-groups full
![2018-10-30_085524](https://user-images.githubusercontent.com/35614700/47698770-ab411200-dc21-11e8-9373-3a7cb6344065.png)

**Server side (please complete the following information):**
 - OS:  4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
 - Python version: Python 3.5.3
 - Version : v0.6
 - Zabbix_server (Zabbix) 4.0.0 Revision 85308 1 October 2018, compilation time: Oct  8 2018 21:05:46

**Additional context**
MSA2052
Firmware: VL100R004,VL100P001
Имеются 4 полки MSA 2052 c кэшем и тирингом, на предыдущих полка 2040 и 2042 информация отображается полностью, правда там нет кэш группы дисков и там базовая лицензия. 
Спасибо за такой шикарный шаблон) готов помочь в разборке данного явления

**Comment by asand3r** [comment]
Привет @mitnoleg 
Я не понял всю проблему. Можно еще раз описать разницу между выводом для 2040 и 2050?

**Comment by mitnoleg** [comment]
Привет @asand3r
В общем данные с MSA 2052 поступают не все, в отличие от MSA 2040
Вот данные на 2052, тут все по нулям, хотя полка в работе.
![image](https://user-images.githubusercontent.com/35614700/49205616-91c9ec00-f3c0-11e8-9d64-e6f9bca5deff.png)
Вот данные на 2040, тут есть данные.
![image](https://user-images.githubusercontent.com/35614700/49205645-aefeba80-f3c0-11e8-8e52-0d097cb97c91.png)
Дополнительно на 2052 есть кэш диск, там он показывает статус 250, а на 2040 у нас нет кэш диска, поэтому не могу сказать, как на 2040 отображается статус кэш диска
![image](https://user-images.githubusercontent.com/35614700/49205706-e2414980-f3c0-11e8-9482-a2ba2382c72e.png)
А так он в морде 2052 отображается
![47698546-ceb78d00-dc20-11e8-9353-38cc91c60f20](https://user-images.githubusercontent.com/35614700/49205949-9216b700-f3c1-11e8-9d8a-0a955ca39e99.png)

**Comment by asand3r** [comment]
@mitnoleg ОК, API отдает честный 0 для данных параметров PSU, значит так там и есть.
Могу посоветовать проверить эти параметры через CLI:
```code
set cli-parameters xml
show power-supplies
```
Если там будут другие числа, отличные от 0 - дай знать.

**Comment by mitnoleg** [comment]
`HPE MSA Storage MSA 2050 SAN
System Name: 
System Location: 
Version: VL100P001
# set cli-parameters json
new APIData([
  new APIStatus([
    new APIProp({name:"response-type",value:"Success"}),
    new APIProp({name:"response-type-numeric",value:"0"}),
    new APIProp({name:"response",value:"Command completed successfully. (2018-11-29 13:34:48)"}),
    new APIProp({name:"return-code",value:"0"}),
    new APIProp({name:"component-id",value:""}),
    new APIProp({name:"time-stamp",value:"2018-11-29 13:34:48"}),
    new APIProp({name:"time-stamp-numeric",value:"1543498488"})],
    {basetype:"status",name:"",oid:"1"})
])
# show power-supplies
new APIData([
  new APIPowerSupplies([
    new APIProp({name:"durable-id",value:"psu_1.1"}),
    new APIProp({name:"enclosure-id",value:"1"}),
    new APIProp({name:"serial-number",value:"7CE727T212"}),
    new APIProp({name:"part-number",value:"814665-001"}),
    new APIProp({name:"description",value:"FRU,Pwr Sply,595W,AC,2U,LC,HP ES"}),
    new APIProp({name:"name",value:"PSU 1, Left"}),
    new APIProp({name:"fw-revision",value:"N/A"}),
    new APIProp({name:"revision",value:"C"}),
    new APIProp({name:"model",value:"814665-001"}),
    new APIProp({name:"vendor",value:""}),
    new APIProp({name:"location",value:"Enclosure 1 - Left"}),
    new APIProp({name:"position",value:"Left"}),
    new APIProp({name:"position-numeric",value:"0"}),
    new APIProp({name:"dash-level",value:""}),
    new APIProp({name:"fru-shortname",value:"AC Power Supply"}),
    new APIProp({name:"mfg-date",value:"2017-05-27 13:57:14"}),
    new APIProp({name:"mfg-date-numeric",value:"1495893434"}),
    new APIProp({name:"mfg-location",value:"Zhongshan,Guangdong,CN"}),
    new APIProp({name:"mfg-vendor-id",value:""}),
    new APIProp({name:"configuration-serialnumber",value:"7CE727T212"}),
    new APIProp({name:"dc12v",value:"0"}),
    new APIProp({name:"dc5v",value:"0"}),
    new APIProp({name:"dc33v",value:"0"}),
    new APIProp({name:"dc12i",value:"0"}),
    new APIProp({name:"dc5i",value:"0"}),
    new APIProp({name:"dctemp",value:"0"}),
    new APIProp({name:"health",value:"OK"}),
    new APIProp({name:"health-numeric",value:"0"}),
    new APIProp({name:"health-reason",value:""}),
    new APIProp({name:"health-recommendation",value:""}),
    new APIProp({name:"status",value:"Up"}),
    new APIProp({name:"status-numeric",value:"0"}),
    new APIFan([
      new APIProp({name:"durable-id",value:"fan_1.1"}),
      new APIProp({name:"name",value:"Fan Loc:left-PSU 1"}),
      new APIProp({name:"location",value:"Enclosure 1 - Left"}),
      new APIProp({name:"status-ses",value:"OK"}),
      new APIProp({name:"status-ses-numeric",value:"1"}),
      new APIProp({name:"extended-status",value:"16"}),
      new APIProp({name:"status",value:"Up"}),
      new APIProp({name:"status-numeric",value:"0"}),
      new APIProp({name:"speed",value:"3780"}),
      new APIProp({name:"position",value:"Left"}),
      new APIProp({name:"position-numeric",value:"0"}),
      new APIProp({name:"serial-number",value:"N/A"}),
      new APIProp({name:"part-number",value:"N/A"}),
      new APIProp({name:"fw-revision",value:""}),
      new APIProp({name:"hw-revision",value:""}),
      new APIProp({name:"locator-led",value:"Off"}),
      new APIProp({name:"locator-led-numeric",value:"0"}),
      new APIProp({name:"health",value:"OK"}),
      new APIProp({name:"health-numeric",value:"0"}),
      new APIProp({name:"health-reason",value:""}),
      new APIProp({name:"health-recommendation",value:""})],
      {basetype:"fan",name:"fan-details",oid:"2"})],
    {basetype:"power-supplies",name:"power-supplies",oid:"2"}),
  new APIPowerSupplies([
    new APIProp({name:"durable-id",value:"psu_1.2"}),
    new APIProp({name:"enclosure-id",value:"1"}),
    new APIProp({name:"serial-number"    new APIProp({name:"part-number",value:"814665-001"}),
    new APIProp({name:"description",value:"FRU,Pwr Sply,595W,AC,2U,LC,HP ES"}),
    new APIProp({name:"name",value:"PSU 2, Right"}),
    new APIProp({name:"fw-revision",value:"N/A"}),
    new APIProp({name:"revision",value:"C"}),
    new APIProp({name:"model",value:"814665-001"}),
    new APIProp({name:"vendor",value:""}),
    new APIProp({name:"location",value:"Enclosure 1 - Right"}),
    new APIProp({name:"position",value:"Right"}),
    new APIProp({name:"position-numeric",value:"1"}),
    new APIProp({name:"dash-level",value:""}),
    new APIProp({name:"fru-shortname",value:"AC Power Supply"}),
    new APIProp({name:"mfg-date",value:"2017-05-27 13:45:13"}),
    new APIProp({name:"mfg-date-numeric",value:"1495892713"}),
    new APIProp({name:"mfg-location",value:"Zhongshan,Guangdong,CN"}),
    new APIProp({name:"mfg-vendor-id",value:""}),
    new APIProp({name:"configuration-serialnumber",value:"7CE727T211"}),
    new APIProp({name:"dc12v",value:"0"}),
    new APIProp({name:"dc5v",value:"0"}),
    new APIProp({name:"dc33v",value:"0"}),
    new APIProp({name:"dc12i",value:"0"}),
    new APIProp({name:"dc5i",value:"0"}),
    new APIProp({name:"dctemp",value:"0"}),
    new APIProp({name:"health",value:"OK"}),
    new APIProp({name:"health-numeric",value:"0"}),
    new APIProp({name:"health-reason",value:""}),
    new APIProp({name:"health-recommendation",value:""}),
    new APIProp({name:"status",value:"Up"}),
    new APIProp({name:"status-numeric",value:"0"}),
    new APIFan([
      new APIProp({name:"durable-id",value:"fan_1.2"}),
      new APIProp({name:"name",value:"Fan Loc:right-PSU 2"}),
      new APIProp({name:"location",value:"Enclosure 1 - Right"}),
      new APIProp({name:"status-ses",value:"OK"}),
      new APIProp({name:"status-ses-numeric",value:"1"}),
      new APIProp({name:"extended-status",value:"16"}),
      new APIProp({name:"status",value:"Up"}),
      new APIProp({name:"status-numeric",value:"0"}),
      new APIProp({name:"speed",value:"3790"}),
      new APIProp({name:"position",value:"Right"}),
      new APIProp({name:"position-numeric",value:"1"}),
      new APIProp({name:"serial-number",value:"N/A"}),
      new APIProp({name:"part-number",value:"N/A"}),
      new APIProp({name:"fw-revision",value:""}),
      new APIProp({name:"hw-revision",value:""}),
      new APIProp({name:"locator-led",value:"Off"}),
      new APIProp({name:"locator-led-numeric",value:"0"}),
      new APIProp({name:"health",value:"OK"}),
      new APIProp({name:"health-numeric",value:"0"}),
      new APIProp({name:"health-reason",value:""}),
      new APIProp({name:"health-recommendation",value:""})],
      {basetype:"fan",name:"fan-details",oid:"4"})],
    {basetype:"power-supplies",name:"power-supplies",oid:"4"}),
  new APIStatus([
    new APIProp({name:"response-type",value:"Success"}),
    new APIProp({name:"response-type-numeric",value:"0"}),
    new APIProp({name:"response",value:"Command completed successfully. (2018-11-29 13:34:59)"}),
    new APIProp({name:"return-code",value:"0"}),
    new APIProp({name:"component-id",value:""}),
    new APIProp({name:"time-stamp",value:"2018-11-29 13:34:59"}),
    new APIProp({name:"time-stamp-numeric",value:"1543498499"})],
    {basetype:"status",name:"",oid:"5])
#  show disk-groups
new APIData([
  new APIDiskGroups([
    new APIProp({name:"name",value:"dgA01"}),
    new APIProp({name:"blocksize",value:"512"}),
    new APIProp({name:"size",value:"14.3TB"}),
    new APIProp({name:"size-numeric",value:"28098035712"}),
    new APIProp({name:"freespace",value:"11.2TB"}),
    new APIProp({name:"freespace-numeric",value:"21923553280"}),
    new APIProp({name:"raw-size",value:"18.0TB"}),
    new APIProp({name:"raw-size-numeric",value:"35163283680"}),
    new APIProp({name:"storage-type",value:"Virtual"}),
    new APIProp({name:"storage-type-numeric",value:"1"}),
    new APIProp({name:"pool",value:"A"}),
    new APIProp({name:"pool-serial-number",value:"00c0ff29972500005cc42a5a01000000"}),
    new APIProp({name:"storage-tier",value:"Standard"}),
    new APIProp({name:"storage-tier-numeric",value:"2"}),
    new APIProp({name:"total-pages",value:"3429936"}),
    new APIProp({name:"allocated-pages",value:"753721"}),
    new APIProp({name:"available-pages",value:"2676215"}),
    new APIProp({name:"pool-percentage",value:"100"}),
    new APIProp({name:"performance-rank",value:"0"}),
    new APIProp({name:"owner",value:"A"}),
    new APIProp({name:"owner-numeric",value:"1"}),
    new APIProp({name:"preferred-owner",value:"A"}),
    new APIProp({name:"preferred-owner-numeric",value:"1"}),
    new APIProp({name:"raidtype",value:"RAID6"}),
    new APIProp({name:"raidtype-numeric",value:"11"}),
    new APIProp({name:"diskcount",value:"10"}),
    new APIProp({name:"sparecount",value:"0"}),
    new APIProp({name:"chunksize",value:"512k"}),
    new APIProp({name:"status",value:"FTOL"}),
    new APIProp({name:"status-numeric",value:"0"}),
    new APIProp({name:"lun",value:"4294967295"}),
    new APIProp({name:"min-drive-size",value:"1798.5GB"}),
    new APIProp({name:"min-drive-size-numeric",value:"3512811521"}),
    new APIProp({name:"create-date",value:"2017-12-08 16:56:55"}),
    new APIProp({name:"create-date-numeric",value:"1512752215"}),
    new APIProp({name:"cache-read-ahead",value:"2199.0GB"}),
    new APIProp({name:"cache-read-ahead-numeric",value:"4294967295"}),
    new APIProp({name:"cache-flush-period",value:"4294967295"}),
    new APIProp({name:"read-ahead-enabled",value:"Enabled"}),
    new APIProp({name:"read-ahead-enabled-numeric",value:"1"}),
    new APIProp({name:"write-back-enabled",value:"Disabled"}),
    new APIProp({name:"write-back-enabled-numeric",value:"0"}),
    new APIProp({name:"job-running",value:""}),
    new APIProp({name:"current-job",value:""}),
    new APIProp({name:"current-job-numeric",value:"0"}),
    new APIProp({name:"current-job-completion",value:""}),
    new APIProp({name:"num-array-partitions",value:"4"}),
    new APIProp({name:"largest-free-partition-space",value:"0B"}),
    new APIProp({name:"largest-free-partition-space-numeric",value:"0"}),
    new APIProp({name:"num-drives-per-low-level-array",value:"1"}),
    new APIProp({name:"num-expansion-partitions",value:"0"}),
    new APIProp({name:"num-partition-segments",value:"0"}),
    new APIProp({name:"new-partition-lba",value:"0B"}),
    new APIProp({name:"new-partition-lba-numeric",value:"0"}),
    new APIProp({name:"array-drive-type",value:"SAS"}),
    new APIProp({name:"array-drive-type-numeric",value:"4"}),
    new APIProp({name:"is-job-auto-abortable",value:"false"}),
    new APIProp({name:"is-job-auto-abortable-numeric",value:"0"}),
    new APIProp({name:"serial-number",value:"00c0ff299725000057c42a5a00000000"}),
    new APIProp({name:"blocks",value:    new APIProp({name:"disk-dsd-enable-vdisk",value:"Disabled"}),
    new APIProp({name:"disk-dsd-enable-vdisk-numeric",value:"0"}),
    new APIProp({name:"disk-dsd-delay-vdisk",value:"0"}),
    new APIProp({name:"scrub-duration-goal",value:"0"}),
    new APIProp({name:"pool-sector-format",value:"512e"}),
    new APIProp({name:"pool-sector-format-numeric",value:"1"}),
    new APIProp({name:"health",value:"OK"}),
    new APIProp({name:"health-numeric",value:"0"}),
    new APIProp({name:"health-reason",value:""}),
    new APIProp({name:"health-recommendation",value:""})],
    {basetype:"disk-groups",name:"disk-group",oid:"1"}),
  new APIDiskGroups([
    new APIProp({name:"name",value:"rcA1"}),
    new APIProp({name:"blocksize",value:"512"}),
    new APIProp({name:"size",value:"1596.5GB"}),
    new APIProp({name:"size-numeric",value:"3118260224"}),
    new APIProp({name:"freespace",value:"830.9GB"}),
    new APIProp({name:"freespace-numeric",value:"1622941696"}),
    new APIProp({name:"raw-size",value:"1600.3GB"}),
    new APIProp({name:"raw-size-numeric",value:"3125648736"}),
    new APIProp({name:"storage-type",value:"Virtual"}),
    new APIProp({name:"storage-type-numeric",value:"1"}),
    new APIProp({name:"pool",value:"A"}),
    new APIProp({name:"pool-serial-number",value:"00c0ff29972500005cc42a5a01000000"}),
    new APIProp({name:"storage-tier",value:"Read Cache"}),
    new APIProp({name:"storage-tier-numeric",value:"8"}),
    new APIProp({name:"total-pages",value:"380647"}),
    new APIProp({name:"allocated-pages",value:"182534"}),
    new APIProp({name:"available-pages",value:"198113"}),
    new APIProp({name:"pool-percentage",value:"0"}),
    new APIProp({name:"performance-rank",value:"0"}),
    new APIProp({name:"owner",value:"A"}),
    new APIProp({name:"owner-numeric",value:"1"}),
    new APIProp({name:"preferred-owner",value:"A"}),
    new APIProp({name:"preferred-owner-numeric",value:"1"}),
    new APIProp({name:"raidtype",value:"RAID0"}),
    new APIProp({name:"raidtype-numeric",value:"0"}),
    new APIProp({name:"diskcount",value:"2"}),
    new APIProp({name:"sparecount",value:"0"}),
    new APIProp({name:"chunksize",value:"512k"}),
    new APIProp({name:"status",value:"UP"}),
    new APIProp({name:"status-numeric",value:"250"}),
    new APIProp({name:"lun",value:"4294967295"}),
    new APIProp({name:"min-drive-size",value:"799.3GB"}),
    new APIProp({name:"min-drive-size-numeric",value:"1561261057"}),
    new APIProp({name:"create-date",value:"2017-12-08 17:13:16"}),
    new APIProp({name:"create-date-numeric",value:"1512753196"}),
    new APIProp({name:"cache-read-ahead",value:"2199.0GB"}),
    new APIProp({name:"cache-read-ahead-numeric",value:"4294967295"}),
    new APIProp({name:"cache-flush-period",value:"4294967295"}),
    new APIProp({name:"read-ahead-enabled",value:"Enabled"}),
    new APIProp({name:"read-ahead-enabled-numeric",value:"1"}),
    new APIProp({name:"write-back-enabled",value:"Disabled"}),
    new APIProp({name:"write-back-enabled-numeric",value:"0"}),
    new APIProp({name:"job-running",value:""}),
    new APIProp({name:"current-job",value:""}),
    new APIProp({name:"current-job-numeric",value:"0"}),
    new APIProp({name:"current-job-completion",value:""}),
    new APIProp({name:"num-array-partitions",value:"1"}),
    new APIProp({name:"largest-free-partition-space",value:"0B"}),
    new APIProp({name:"largest-free-partition-space-numeric",value:"0"}),
    new APIProp({name:"num-drives-per    new APIProp({name:"num-expansion-partitions",value:"0"}),
    new APIProp({name:"num-partition-segments",value:"0"}),
    new APIProp({name:"new-partition-lba",value:"0B"}),
    new APIProp({name:"new-partition-lba-numeric",value:"0"}),
    new APIProp({name:"array-drive-type",value:"sSAS"}),
    new APIProp({name:"array-drive-type-numeric",value:"8"}),
    new APIProp({name:"is-job-auto-abortable",value:"false"}),
    new APIProp({name:"is-job-auto-abortable-numeric",value:"0"}),
    new APIProp({name:"serial-number",value:"00c0ff29972500002cc82a5a00000000"}),
    new APIProp({name:"blocks",value:"3122454528"}),
    new APIProp({name:"disk-dsd-enable-vdisk",value:"Disabled"}),
    new APIProp({name:"disk-dsd-enable-vdisk-numeric",value:"0"}),
    new APIProp({name:"disk-dsd-delay-vdisk",value:"0"}),
    new APIProp({name:"scrub-duration-goal",value:"0"}),
    new APIProp({name:"pool-sector-format",value:"512e"}),
    new APIProp({name:"pool-sector-format-numeric",value:"1"}),
    new APIProp({name:"health",value:"OK"}),
    new APIProp({name:"health-numeric",value:"0"}),
    new APIProp({name:"health-reason",value:""}),
    new APIProp({name:"health-recommendation",value:""})],
    {basetype:"disk-groups",name:"disk-group",oid:"2"}),
  new APIStatus([
    new APIProp({name:"response-type",value:"Success"}),
    new APIProp({name:"response-type-numeric",value:"0"}),
    new APIProp({name:"response",value:"Command completed successfully. (2018-11-29 13:40:03)"}),
    new APIProp({name:"return-code",value:"0"}),
    new APIProp({name:"component-id",value:""}),
    new APIProp({name:"time-stamp",value:"2018-11-29 13:40:03"}),
    new APIProp({name:"time-stamp-numeric",value:"1543498803"})],
    {basetype:"status",name:"",oid:"3"})
])
# show disk-group-statistics
new APIData([
  new APIDiskGroupStatistics([
    new APIProp({name:"serial-number",value:"00c0ff299725000057c42a5a00000000"}),
    new APIProp({name:"name",value:"dgA01"}),
    new APIProp({name:"time-since-reset",value:"4294967"}),
    new APIProp({name:"time-since-sample",value:"29"}),
    new APIProp({name:"number-of-reads",value:"54571209"}),
    new APIProp({name:"number-of-writes",value:"414633568"}),
    new APIProp({name:"data-read",value:"54.7TB"}),
    new APIProp({name:"data-read-numeric",value:"54711090596864"}),
    new APIProp({name:"data-written",value:"106.6TB"}),
    new APIProp({name:"data-written-numeric",value:"106660664040448"}),
    new APIProp({name:"bytes-per-second",value:"387.0KB"}),
    new APIProp({name:"bytes-per-second-numeric",value:"387072"}),
    new APIProp({name:"iops",value:"2"}),
    new APIProp({name:"avg-rsp-time",value:"18842"}),
    new APIProp({name:"avg-read-rsp-time",value:"18842"}),
    new APIProp({name:"avg-write-rsp-time",value:"18028"}),
    new APIDiskGroupStatisticsPaged([
      new APIProp({name:"serial-number",value:"00c0ff299725000057c42a5a00000000"}),
      new APIProp({name:"pages-alloc-per-minute",value:"1"}),
      new APIProp({name:"pages-dealloc-per-minute",value:"0"}),
      new APIProp({name:"pages-reclaimed",value:"0"}),
      new APIProp({name:"num-pages-unmap-per-minute",value:"0"})],
      {basetype:"disk-group-statistics-paged",name:"disk-group-statistics-paged",oid:"2"})],
    {basetype:"disk-group-statistics",name:"disk-group-statistics",oid:"2"}),
  new APIDiskGroupStatistics([
    new APIProp({name:"serial-number",value:"00c0ff29972500002cc82a5a00000000"}),
    new APIProp({name:"name",value:"rcA1"}),
    new APIProp({name:"time-since-reset",value:"4294967"}),
    new APIProp({name:"time-since-sample",value:"29"}),
    new APIProp({name:"number-of-reads",value:"622932179"}),
    new APIProp({name:"number-of-writes",value:"362509567"}),
    new APIProp({name:"data-read",value:"237.9TB"}),
    new APIProp({name:"data-read-numeric",value:"237933316626432"}),
    new APIProp({name:"data-written",value:"77.9TB"}),
    new APIProp({name:"data-written-numeric",value:"77965165538304"}),
    new APIProp({name:"bytes-per-second",value:"556.0KB"}),
    new APIProp({name:"bytes-per-second-numeric",value:"556032"}),
    new APIProp({name:"iops",value:"4"}),
    new APIProp({name:"avg-rsp-time",value:"552"}),
    new APIProp({name:"avg-read-rsp-time",value:"552"}),
    new APIProp({name:"avg-write-rsp-time",value:"456"}),
    new APIDiskGroupStatisticsPaged([
      new APIProp({name:"serial-number",value:"00c0ff29972500002cc82a5a00000000"}),
      new APIProp({name:"pages-alloc-per-minute",value:"0"}),
      new APIProp({name:"pages-dealloc-per-minute",value:"0"}),
      new APIProp({name:"pages-reclaimed",value:"0"}),
      new APIProp({name:"num-pages-unmap-per-minute",value:"0"})],
      {basetype:"disk-group-statistics-paged",name:"disk-group-statistics-paged",oid:"4"})],
    {basetype:"disk-group-statistics",name:"disk-group-statistics",oid:"4"}),
  new APIStatus([
    new APIProp({name:"response-type",value:"Success"}),
    new APIProp({name:"response-type-numeric",value:"0"}),
    new APIProp({name:"response",value:"Command completed successfully. (2018-11-29 13:42:45)"}),
    new APIProp({name:"return-code",value:"0"}),
    new APIProp({name:"component-id",value:""}),
    new APIProp({name:"time-stamp",value:"2018-11-29 13:42:45"}),
    new APIProp({name:"time-stamp-numeric",value:"1543498965"})],
    {basetype:"status",name:"",oid:"5"})
])

`

**Comment by asand3r** [comment]
@mitnoleg Ну вот, везде нули.

**Comment by mitnoleg** [comment]
А по поводу статуса у кэш дисков?
new APIProp({name:"name",value:"rcA1"})
new APIProp({name:"status",value:"UP"}),
new APIProp({name:"status-numeric",value:"250"}),
new APIProp({name:"health",value:"OK"}),
new APIProp({name:"health-numeric",value:"0"}),
new APIProp({name:"health-reason",value:""}),

**Comment by asand3r** [comment]
Какой команде в cli это эквивалентно?

**Comment by mitnoleg** [comment]
На полке 2 группы дисков, одна все диски и вторая из 2 дисков это кэш для тиринга
Различия вывода в при **show disk-groups** заключается в следующих строках
![image](https://user-images.githubusercontent.com/35614700/49266869-d9a44e00-f468-11e8-9045-661e406a89b2.png)

С правой стороны - это общая группа дисков для данных, с другой стороны - это группа дисков кэш и тиринга, в шаблоне привязывается, как я понял к значению  
new APIProp({name:"status-numeric",value:"250"}), поэтому срабатывает тригер {Template HPE MSA for Zabbix 4.0:msa.dg["{#DG.ID}","status-num"].avg(#3)}<>0 , необходимо добавить условие, что не равен 250 в шаблон

Статистика по дисковым группам показывается по команде **show disk-group-statistics**
Тут тоже так, с правой стороны - это общая группа дисков для данных, с другой стороны - это группа дисков кэш и тиринга
![image](https://user-images.githubusercontent.com/35614700/49267385-415b9880-f46b-11e8-812a-7618e014a187.png)

Интересны строки по объему записанного и прочитанного, можно видеть соотношение запись /чтение на дисковые группы, плюc соотношение iops между кэшем и остальными группами дисков, покажет эффективность.
В веб морде есть такое отображение производительности тиринга.
![2018-11-30_065038](https://user-images.githubusercontent.com/35614700/49267595-5a187e00-f46c-11e8-9cea-f28e253756f8.png)

Файлы, которые сравнивал.
[new 52.txt](https://github.com/asand3r/zbx-hpmsa/files/2631949/new.52.txt)
[1111111111111.txt](https://github.com/asand3r/zbx-hpmsa/files/2631950/1111111111111.txt)
[new 51.txt](https://github.com/asand3r/zbx-hpmsa/files/2631951/new.51.txt)
[new 50.txt](https://github.com/asand3r/zbx-hpmsa/files/2631952/new.50.txt)

**Comment by asand3r** [comment]
Привет @mitnoleg.
Извини, только сейчас добрался до просмотра Issue в репозитории.
Давай по порядку. Как я понял - у нас две проблемы.
1. Шаблон агрится на status-numeric 250, хотя по докам 250 - это состояние UP.
![screenshot_20190105_114130](https://user-images.githubusercontent.com/13959303/50722424-d7748580-10df-11e9-92d4-7dc34f8e2f3c.png)
Простое изменение триггера наверное будет не самым лучшим решением. Я бы добавил для 2050+ в данные LLD признак того, к какому типу Storage Tier он принаджелит - Read Cache, Standard и т.д.
![default](https://user-images.githubusercontent.com/13959303/50722458-671a3400-10e0-11e9-896a-7ac66cd42149.png)

2. Второй вопрос по расширению данных с собираемой статистикой. Я бы хотел чтобы он рассматривался отдельно, поэтому попрошу вынести его в отдельнй пул-реквест с подробным описанием необходимых параметров.

**Comment by mitnoleg** [comment]
Добрый день, хотелось бы уточнить по поводу  1 вопроса, как это сделать хотя бы примерно

**Comment by asand3r** [comment]
Добрый. ) Прошу прощения, сейчас совсем нет времени заниматься поддержкой скрипта, поэтому торможу с решением проблем.
Я хотел добавить макрос вроде {#STORAGE.TYPE} по которому можно было бы определять тип стораджа и, может быть, делать разные дискавери с созданием собственных триггеров.

**Comment by mitnoleg** [comment]
Добрый) Наверное в Pools discovery надо будет добавить {#STORAGE.TYPE}  и уже исходя из них разные элементы данных. С питоном у меня плоховато, пытался запилить получении информации о прошивке диска и размере дисков,и с контроллерами.

**Comment by asand3r** [comment]
Привет @mitnoleg. Я выложил версию v0.6.6, думаю, что она закроет проблему с неверным триггером для Read Cache дисковых групп.

**Comment by mitnoleg** [comment]
Привет, спасибо, постараюсь в скором времени обновить и отписаться о результатах тут

**Comment by asand3r** [comment]
@mitnoleg обрати внимание, что нужно так обновить шаблон или поправить имеющийся на использование контекстных триггеров:
![изображение](https://user-images.githubusercontent.com/13959303/55305929-08542480-545b-11e9-96d9-e7822196ef72.png)
