### ISSUE TITLE
SSL Flag not working when running

### ISSUE THREAD

**Issue by damo2929** [asand3r/zbx-hpmsa#16]
issue is the script doesn't like the --ssl direct flag when ran by zabbix 

zbx-hpmsa.py["--ssl direct","-a", "{$API.VER}", "-u", "{$MSA.USERNAME}", "-p", "{$MSA.PASSWORD}", "full", "{HOST.CONN}", "volumes"]

returns

usage: zbx-hpmsa.py [-h] [-a {1,2}] [-u USERNAME] [-p PASSWORD]
                    [-f LOGIN_FILE] [-v] [-s SAVE_XML] [-t TMP_DIR]
                    [--ssl {direct,verify}]
                    {install,cache,lld,full,health} ...
zbx-hpmsa.py: error: argument command: invalid choice: '--ssl direct' (choose from 'install', 'cache', 'lld', 'full', 'health')

when ran on the command line this error doesn't happen please can you advise how to address this of if it's a script problem

**Comment by asand3r** [comment]
Hi @damo2929 
I think the problem is in incorrect key format. It must be"
zbx-hpmsa.py["--ssl", "direct","-a", ......]
