### ISSUE TITLE
Adding more low-level statistical info

### ISSUE THREAD

**Issue by zimage** [asand3r/zbx-hpmsa#18]
I would like to monitor more realtime data usage than just controller-level IOPS. I am able to view statistics in the MSA's web-portal about disk-group and pool block allocation, per-disk reads/s and writes/s, cache hits and misses, etc. I'd like to be able to view these same statistics in zabbix.

I have already modified my local copy of zbx-hpmsa.py to add the following controller-level stats.
* number-of-reads
* number-of-writes
* data-read-numeric
* data-written-numeric
* read-cache-hits
* read-cache-misses
* write-cache-hits
* write-cache-misses

I still need to modify the template

I would like to fork this project, and be able to contribute my changes back to this main branch. What issues would you need me to consider in order for you to approve my pull request?

**Comment by asand3r** [comment]
Hi @zimage.
You needn't create any issues. Just fork my repo, make all changes you need and send me a pool request. I'll surely check it and accept it if all be fine. =)
I've checked your repository and now your copy is the same as my.
