### ISSUE TITLE
ERROR: (get_skey) Could not connect

### ISSUE THREAD

**Issue by reginfo** [asand3r/zbx-hpmsa#2]
Hi, 

I`m trying to set up this new script for new unit

I`m executing script: /usr/bin/python3.6 zbx-hpmsa.py --discovery --msa 192.168.152.7 --component vdisks --user zabbix --password ********

but I`ve got :

ERROR: (get_skey) Could not connect to http://192.168.152.7/api/login/501d5b92e3f722af002a429cf4caf490

Can you help me?

OS : CentOS 7

----
UPD : Can it be related to HTTPS?

**Comment by asand3r** [comment]
Hi, @reginfo 
Is device configured to communicate through HTTP? In 'get_skey' function we just make simple GET request to API, so the most possible reason is missing network connection or disabled HTTP.

**Comment by reginfo** [comment]
only https for security purposes. so there is a mistake?

**Comment by asand3r** [comment]
Yeap, that's right. Right now the script doesn't support connections over HTTPS, sorry. ) I'm planning to add that functionality later.

**Comment by asand3r** [comment]
@reginfo 
Hello again. Could you tell me which kind of certificates do you using with MSA? Is it self-singed or singed by your local CA?

**Comment by reginfo** [comment]
Hi,

It is CU unit and it is signed using self-signed certificate.

**Comment by asand3r** [comment]
Hmm, I've added HTTPS support to DEV branch, but it works with limitations:
1. Supports only MSA with single controller. Or controller FQDN name shouldn't be Round-robin DNS record;
2. Operating system, where we executing the script should have possibility to verify Installed certificate. So, it will not work with self-signed cerificates.
3. Login caching feature is disabled for HTTPS right now.

**Comment by reginfo** [comment]
I will talk with CU  about this in new 2018 year.

**Comment by asand3r** [comment]
@reginfo OK, so, I'm closing this issue. You can follow changes about HTTPS support, I'm plan to work with it more.
