### ISSUE TITLE
HP MSA2012fc old

### ISSUE THREAD

**Issue by alevial** [asand3r/zbx-hpmsa#20]
Здравствуйте, 
ошибка при выполнении скрипта:
![изображение](https://user-images.githubusercontent.com/49550047/56020297-7debaa80-5d0f-11e9-97b2-adf45c7b6518.png)

**Server side (please complete the following information):**
 - OS: Debian 9.6 (Zabbix 4.0)
 - Python version: [e.g. 3.5]
 - Version [e.g. v0.6.6]
pip 19.0.3 from /usr/local/lib/python3.5/dist-packages/pip-19.0.3-py3.5.egg/pip (python 3.5)

**Comment by asand3r** [comment]
Приветствую @alevial.
Стоит попробовать запустить с параметром "-a 1", если это модель времён P2000G3.

**Comment by alevial** [comment]
ничего не поменялось:
![изображение](https://user-images.githubusercontent.com/49550047/56035561-36771580-5d33-11e9-8c76-fabd3a1a09ad.png)

подробнее об СХД:

![изображение](https://user-images.githubusercontent.com/49550047/56035900-1b58d580-5d34-11e9-9a5a-e192a885f485.png)

![изображение](https://user-images.githubusercontent.com/49550047/56035935-2ad81e80-5d34-11e9-9374-f13609e04d53.png)

**Comment by asand3r** [comment]
OK, я не тестировал работу с этим устройством.
Попробуй выполнить следующие действия:
1. Получить md5 от пары "логин:пароль"
2. Выполнить HTTP запрос по адресу: http://msa_ip_address/api/login/md5'
3. Покажи ответ от API
![изображение](https://user-images.githubusercontent.com/13959303/56036598-f06f8100-5d35-11e9-8d49-8445548adb91.png)

**Comment by alevial** [comment]
Ответ железки:
![изображение](https://user-images.githubusercontent.com/49550047/56063096-08b3c000-5d77-11e9-9156-8f39adfa5b7b.png)
использовал пару login:pass а также login_pass ответ идентичный 
md5 получил отсюда:
https://www.md5online.org/

**Comment by asand3r** [comment]
Значит мой скрипт нельзя использовать для этой модели. К сожалению, у меня нет под рукой такого девайса, чтобы изучить API и сказать наверняка, но судя по всему это так, да.

**Comment by alevial** [comment]
жаль...
но все равно спасибо, попробую поискать что то другое
