### ISSUE TITLE
ssl direct issue

### ISSUE THREAD

**Issue by 0ziriss** [asand3r/zbx-hpmsa#21]
Hi,
Dont know how to contact you differently, but i am stuck with zbx-hpmsa.

When i put --ssl dircet it says: ERROR: -10027 : The user is not recognized on this system.
when i put --ssl verify it says: Cannot verify storage SSL Certificate.

Dont know why ssl direct is not working.

Cany you pls help?

Regards

**Comment by asand3r** [comment]
Hi @0ziriss.
Does it works without SSL?

**Comment by 0ziriss** [comment]
Hi @asand3r , 
do you mean like this
zbx-hpmsa.py["-a", "{$API.VER}", "-u", "{$MSA.USERNAME}", "-p", "{$MSA.PASSWORD}", "full", "{HOST.CONN}", "controllers"]
?

**Comment by asand3r** [comment]
OK, first thing - what's your MSA model?
And yes, try to check it's support with console, e.g.:
```bash
./zbx-hpmsa.py full MSA-IP disks
```

**Comment by 0ziriss** [comment]
Hi @asand3r 
Model is MSA 2040
 
 Cannot connect to storage HTTPConnectionPool(host='IP', port=80): Max retries exceeded with url: /api/login/XXXXXXXXXXXXXXXXXXXXXXXX (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe3ea14a8d0>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by asand3r** [comment]
Good, probably HTTP is disabled, so you must use HTTPS or enable HTTP.
HTTPS with MSA 2040 works fine in my environment. Do you entered your user and password correctly?
```bash
./zbx-hpmsa.py -u USERNAME -p PASSWORD full MSA-IP disks
```

**Comment by 0ziriss** [comment]
yes the username and password are correct.
it also says ERROR: unable to open database file

**Comment by asand3r** [comment]
Let's start with beginning.
1. Download latest version of my script - v0.6.7
2. Place it to the /usr/lib/zabbix/externalscripts folder
3. Make it executable (chmod +x zbx-hpmsa.py)
4. Run preparing task:
```bash
./zbx-hpmsa.py install
```
5. Check the result with one of commands above, e.g.:
```bash
./zbx-hpmsa.py -u USERNAME -p PASSWORD full MSA-IP disks
```

**Comment by asand3r** [comment]
Oh, yeah, one thing: if your password contains some characters like '$!' and other bash symbols, it must be screening. E.g.:
```bash
./zbx-hpmsa.py -u monitor -p \!monitor full shv-str01 disks
```

**Comment by 0ziriss** [comment]
Hi, 
Ok, now it is working, but in zabbix shows like this:

{"XX":{"health-num":"XX","temperature":"XX","power-on-hours":"XXX","job-running-numeric":"XX",

it is not normal form?

**Comment by asand3r** [comment]
Yep, that's OK. Preprocessing rule will create dependent items with JSONPath steps which will extract all needed values.

**Comment by 0ziriss** [comment]
hi @asand3r ,
I think now is everything ok.
Thank you for your help and for your scripts :)
keep the good work :)
Regards

**Comment by asand3r** [comment]
Have fun. =)

**Comment by Justify87** [comment]
how can I prevent "unverified cert" warning? (replacing cert is not an option)
