### ISSUE TITLE
ERROR: unable to open database file

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [asand3r/zbx-hpmsa#24]
After reboot script gets a error. 
```
ERROR: unable to open database file
ERROR: unable to open database file
ERROR: unable to open database file
```

 - OS: CentOS 7
 - Python version: 3.4
 - Version 0.6.5

Could you fix that issue please? It is a bit annoying to reinstall zbx-hpmsa after every reboot. 

Thank you,

**Comment by asand3r** [comment]
Hi @BroadbandCommunicationsNorth 
Sorry, I've just seen your issue. Yeap, I've moved temp dir to /var/tmp/zbx-hpmsa to solve this problem in v0.6.7 version.
