### ISSUE TITLE
Error Trying to import Zabbix 4 Template

### ISSUE THREAD

**Issue by flpfandrade** [asand3r/zbx-hpmsa#25]
**Describe the bug**
Hello asand3r, thanks for your great work!

I have a zabbix 4.0.5 with your v0.6.6 and zabbix 4.0 template running ok.

I am trying to update to version v0.6.7/v0.6.8. the Python script is running ok and created the cache database on /var/tmp/zbx-hpmsa.

My problem is when i try to import teh updated templates. i Receive a message:
Invalid tag "/zabbix_export/version": unsupported version number.

Tryed to chage to version 4.0 on the xml file but receive the message:
Invalid tag "/zabbix_export/templates/template(1)": unexpected tag "tags".

**Screenshots**

![Import-erro-1](https://user-images.githubusercontent.com/51410344/58962656-091e7500-8782-11e9-8167-9afa3dc4f3e4.PNG)
![Import-erro-2](https://user-images.githubusercontent.com/51410344/58962680-13407380-8782-11e9-8425-b573d22dab82.PNG)

*Server side (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810
 - Python version: 3.6
 - Version v0.6.7 and v0.6.8

**Additional context**

**Comment by asand3r** [comment]
Hi, @flpfandrade.
Yeap, I know. Sorry, I've exported template from 4.2 and now it's minimal supported version with 0.6.8+. You can take template for 4.0 from 0.6.6 or 0.6.7 releases.

**Comment by asand3r** [comment]
I've moved templates to master branch from 0.6.6.

**Comment by flpfandrade** [comment]
Hi thanks for the support!

Can I use the v0.6.6 template with the Python script form version 0.6.8 running?

**Comment by asand3r** [comment]
Yes, it will work, but 0.6.7 and 0.6.8 contains a couple of important changes, such adding new item prototypes. You can check their release notes and implement it yourself or wait while I'm install 4.0. again and export correct template version again.
