### ISSUE TITLE
The Storage Controller is not ready for the operation

### ISSUE THREAD

**Issue by idShura** [asand3r/zbx-hpmsa#27]
В настройках хоста у меня указаны адреса двух контролеров. Первым указан контролер A. 
Насколько я понимаю, для мониторинга используется, ip адрес только одного из контролеров (HOST.CONN), в моем случае это контролера А.

Контролер А вышел из строя, и при этом контролер отвечает на пинг.
Item **MSA JSON controllers full** стал возвращать ошибку:
`ERROR: -10059 : The Storage Controller is not ready for the operation.`

В Zabbix не было сгенерировано ни одной проблемы. После того, как я изменил порядок ip адресов контролеров, установив первым контролер B - проблемы были сгенерированы.

Наверное, нужно:
1. предусмотреть работу с двумя контролерами в скрипте **zbx-hpmsa.py**, чтобы в случае недоступности или ошибки с одним контролером, пробовать получить данные с другого контролера.
2. Создать триггер для проверки данных в **MSA JSON controllers full**

**Comment by asand3r** [comment]
Привет, @idShura 
В моей среде так же используются устройства с двумя контроллерами и я решил эту проблему через DNS Round-Robin. Т.е. в DNS созданы две A записи с одним именем на IP каждого контроллера, а в настройках хоста указано подключаться по DNS имени. Соответственно, опрос устройства ведется сразу по двум адресам поочередно.

**Comment by idShura** [comment]
Да, так можно сделать, но хотелось бы дополнительный контроль "из коробки" (хотя бы проверку **MSA JSON**), чтобы не прошляпить выход из строя оборудования.
Думаю вопрос можно закрыть, спасибо.

**Comment by asand3r** [comment]
OK, я как раз думаю над тем, чтобы сделать триггер на код возврата ответа - "-10059" в твоем случае. Возможно, это так же будет решением.
