### ISSUE TITLE
Getting error while importing to zabbix 4.4.4

### ISSUE THREAD

**Issue by jimeshm** [asand3r/zbx-hpmsa#28]
**Describe the bug**
Cannot read XML: (68) StartTag: invalid element name [Line: 4 | Column: 2].

**Screenshots**
![image](https://user-images.githubusercontent.com/55339122/71553299-4ce50e80-2a33-11ea-9cb8-0bd5948f0098.png)

**Server side (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version zabbix version 4.4.4

**Additional context**
Getting alert while importing template to zabbix 4.4.4

**Comment by zimage** [comment]
The "Template HPE MSA for Zabbix 4.2 with SSL.xml" file contains git conflict test.

**Comment by asand3r** [comment]
Yeap, the template file was broker, sorry about that. I've just uploaded new templates for 4.2 and 4.4 versions.
