### ISSUE TITLE
Perl Error

### ISSUE THREAD

**Issue by MrHupsing** [asand3r/zbx-hpmsa#3]
Hello,

I`ve tried to use the script on our Debian v8.9 server running zabbix v3.0.12

I ran into the problem that the perl script isnt running on the command line.
Error for LLD is
Can't use string ("1") as a HASH ref while "strict refs" in use at hp-msa.pl line 34.
Error for STATS is
Not a HASH reference at hp-msa.pl line 61.

Any idea whats the problem?
Big thanks in advanced ....

Best regards
Sebastian

**Comment by MrHupsing** [comment]
sorry - my failure - i used the false window - please forget the issue - it can be delete

**Comment by asand3r** [comment]
@MrHupsing Hi,
Glad to hear it, but you know - it's absolutely other project. =) It's zbx-hpmsa written with Python, not Perl. =)

**Comment by MrHupsing** [comment]
hi alex,

yeah i know - shame on me :)

do you have any information if your implementation also runs on the old hp
msa's like msa2324sa like the one in my test lab?

best regards and thumbs up ...
sebastian

2018-01-16 15:54 GMT+01:00 Alexander <notifications@github.com>:

**Comment by asand3r** [comment]
@MrHupsing 
Sorry, didn't test it any than HPE MSA2040 and MSA2050. You can simply try it. =) Need's just requests library and lxml (can be simply replaced with builtin xml module).
But, as I know it has different mechanism of authorization, so even if XML structure is the same, you just cannot pass authorization with my script.
You can try to execute something like that:
curl -v -H 'Cookie: wbisessionkey=0fd1795932bbd3905c5d7439ad9ae4fd; wbiusername=manage' http://10.0.0.2/api/show/vdisks
where "0fd1795932bbd3905c5d7439ad9ae4fd" is your auth token. If it works fine and return XML response - please, send it to me and I'll try to check can I add support of this device to my script.
