### ISSUE TITLE
Access Denied api/login

### ISSUE THREAD

**Issue by MattiaMunari** [asand3r/zbx-hpmsa#33]
**Describe the bug**
After configuring everithyng I am able to see values from command line

# ./zbx-hpmsa.py -u monitor -p aaa -ssl=direct lld x.x.x.x disks
{"data":[{"{#DISK.ID}":"1.1","{#DISK.SN}":"L0K8DAYJ","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.2","{#DISK.SN}":"W471577T0000E8149YS0","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.3","{#DISK.SN}":"L0K9SXRJ","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.4","{#DISK.SN}":"L0K9WKSK","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.5","{#DISK.SN}":"L0K9W04K","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.6","{#DISK.SN}":"L0K8G6GJ","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.7","{#DISK.SN}":"L0K9W59K","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.8","{#DISK.SN}":"W471577H0000E8152EUR","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.9","{#DISK.SN}":"69U0A06ZF9ZF","{#DISK.MODEL}":"EH000900JWHPP","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.10","{#DISK.SN}":"69U0A079F9ZF","{#DISK.MODEL}":"EH000900JWHPP","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.11","{#DISK.SN}":"69U0A094F9ZF","{#DISK.MODEL}":"EH000900JWHPP","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.12","{#DISK.SN}":"W47145R20000E810CGQC","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.13","{#DISK.SN}":"W47116RH0000E8089W0H","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.14","{#DISK.SN}":"W471172L0000E8089V54","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.15","{#DISK.SN}":"L0K9WJ3K","{#DISK.MODEL}":"MM1000FECVH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.16","{#DISK.SN}":"W47116PC0000E8089VT0","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.17","{#DISK.SN}":"W47116VS0000E80898K9","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"},{"{#DISK.ID}":"1.18","{#DISK.SN}":"W47145GB0000E810FKTZ","{#DISK.MODEL}":"MM1000JFJTH","{#DISK.ARCH}":"HDD"}]}

but I'm not able to get it work in zabbix. I configured password in macro value (even if the password value in command line doesnt matter (I can enter any vaule and I get the same result) and I obtain this errore in the History of "Latest data in zabbix 4.0.20

ERROR: Cannot connect to storage HTTPSConnectionPool(host='x.x.x.x', port=443): Max retries exceeded with url: /api/login/c4ab3a5e84febbda5b9cf4ab23d86c72 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd6d028a278>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Server side (please complete the following information):**
 - OS: Ubuntu
 - Python version: 3.6.7-1~18.04
 - Version 0.7

**Comment by asand3r** [comment]
Hi @MattiaMunari.
1. Script result that you send above got from your zabbix server or from somewhere else?
2. Do you use template for SSL version - Template HPE MSA for Zabbix 4.0 with SSL.xml?
