### ISSUE TITLE
Permision denied

### ISSUE THREAD

**Issue by proovek** [asand3r/zbx-hpmsa#34]
Hello,
Ive a problem with your script i mean with privileges to it.
Zabix says:
/usr/lib/zabbix/externalscripts/zbx-hpmsa.py: [13] Permission denied

And im wondering which permissions i just need to add.

**Comment by proovek** [comment]
New error:

05/15/2020 11:50:13 AM | /usr/lib/zabbix/externalscripts/zbx-hpmsa.py: line 1: syntax error near unexpected token `newline'/usr/lib/zabbix/externalscripts/zbx-hpmsa.py: line 1: `<html lang="en">'
-- | --



After added X permision to file in linux.

**Comment by asand3r** [comment]
Hello @proovek 
Sorry, it's not the script or Zabbix issue, you must fix it yourself on your Zabbix host.

**Comment by proovek** [comment]
Hmmm but what's wrong?
