### ISSUE TITLE
Zabbix Host Configuration

### ISSUE THREAD

**Issue by negesti** [asand3r/zbx-hpmsa#4]
hi, 

I have manually created a zabbix host configuration for my MSA2050 and "monitor" both controllers using SNMP.
As your template looks really nice I trying to change my config and monitor the device using the XML API. 

I have copied the necessary file to my zabbix server and can manually get the data from my msa and  added the template you provide in this repo to the host.
But as this is a discovery template i get no data :(

Maybe you can provide some more details how to configure this great tool inside zabbix?

**Comment by asand3r** [comment]
Hi, @negesti 
Hmm, I've read your message I got that you copied zbx-hpmsa.py to the 'externalscripts' folder and it works as you expected, right? I mean, if you are using it in command line you can seeing results from your HPE MSA device. So, the problem in what data is missing with my template and LLD, isn't what?
Have you read wiki page about the script installation steps?
https://github.com/asand3r/zbx-hpmsa/wiki/Requirements-and-Installation

**Comment by negesti** [comment]
Exactyl. If I execute the script from bash i can query all data from my MSA 2052. 
I have imported the template into my zabbix server and added it to the host config but I only see 5 discovery rules and no item, graph or triggers for the host.

Next step was to create a discovery rule for my msa controllers but I don't see any data/errors/info there :(

My problem is "only" the config inside zabbix

**Comment by asand3r** [comment]
OK, so LLD doesn't works.
Check permissions on '/var/tmp/zbx-hpmsa/zbx-hpmsa.cache.db' file. It must be 'rw' for user who running zabbix-server:
-rw-r--r--. 1 zabbix zabbix 3072 Mar 12 12:38 zbx-hpmsa.cache.db
If it's not true, change it and also change timeout for discovery rules in the template in 1m for testing.

**Comment by negesti** [comment]
Both the script and the db file look good. Tried it with chmod 777 too. but no luck :(

I have now enabled http on my msa and re-configured the template to use the ip directly (Thought the problem has something to do with the snmp interfaces) and increased the zabbix log level. 

Relevant logs: https://gist.github.com/negesti/d6132dcd5fc78c629541010d4f06a496

As far as i can tell, it creates a new item for the correct host but then fails when getting the data?

    in zbx_activate_item_host() hostid:10246 itemid:48608 type:10

**Comment by asand3r** [comment]
Yeap, I forget to say it - template configured for using with HTTP only and user 'monitor' with password '!monitor'. DNS name or IP address can be used, it doesn't matter.
OK, let's going from beginig. Please, run this in shell:
$ ./zbx-hpmsa.py -m <DNS or IP> -d -c controllers
and paste result here.

P.S. If you have telegram account, we can discuss the problem there. It will be faster. =)

**Comment by negesti** [comment]
I have re-installed the template and script (using the github release zip) and now the discovery rules are working. 

sry
