### ISSUE TITLE
HPE MSA Template though zabbix-proxy

### ISSUE THREAD

**Issue by MarcoVPereira** [asand3r/zbx-hpmsa#40]
Hello asand3r, shurely this not the place to put this question, but I didn´t find anywhere else.
In our environment we have a MSA 2050 off-premises and also a zabbix-proxy. how can I get this template to work?

**Comment by asand3r** [comment]
Hi @MarcoVPereira. It doesn't matter where you host placed - behind Zabbix Proxy or not. But if so, just put the script in externalscripts directory on proxy, that's all you need.

**Comment by MarcoVPereira** [comment]
Thank you asand3r.

**Comment by MarcoVPereira** [comment]
Thanks for your help.
