### ISSUE TITLE
Cannot find host interface on "HP Storage P2000" for item key "msa.contact".

### ISSUE THREAD

**Issue by indreek** [asand3r/zbx-hpmsa#7]
What am i missing in configuration. Using zabbix 4 Alpha9.

Thanks

**Comment by asand3r** [comment]
Hi, @indreek 

Item msa.contact - it's SNMP item. So, you need to add SNMP interface to the host:
![default](https://user-images.githubusercontent.com/13959303/43961080-a6249480-9cbc-11e8-92aa-950887a7cea8.png)
